site_name: SocratesCode Development Docs
# site_url: https://mydomain.org/mysite - to be added later
theme:
  name: material
  features:
    - navigation.sections
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format